name: Run Stock Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib statsmodels scikit-learn

    - name: Run Time Series Analysis
      run: python Time_Series_Analysis.py

    - name: Upload plots as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stock-plots
        path: plots/
